# =============================================================================
# Development Override Configuration
# =============================================================================
# Use for local development: docker-compose up
# Automatically loaded by docker-compose
# =============================================================================

version: '3.8'

services:
  mcp-server:
    # Use local build for development
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - mcp-server:latest
    
    # Mount source code for hot reload
    volumes:
      - ./mcp_server:/app/mcp_server:ro
      - ./tests:/app/tests:ro
      - ./scripts:/app/scripts:ro
      - ./config:/app/config:ro
    
    # Development environment variables
    environment:
      DEVELOPMENT_MODE: 'true'
      DEBUG: 'true'
      LOG_LEVEL: DEBUG
      # Disable production optimizations
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
    
    # Exposed ports for debugging
    ports:
      - "8080:8080"    # API
      - "9090:9090"    # Metrics
      - "5678:5678"    # Python debugger
    
    # Override command for development
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "mcp_server.server"]
    
    # Disable resource limits in development
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G

  prometheus:
    # Development Prometheus config
    volumes:
      - ./docker/prometheus-dev.yml:/etc/prometheus/prometheus.yml:ro
    
    # More verbose logging
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--log.level=debug'
