global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'security-mcp-server'
    static_configs:
      - targets: ['security-mcp-server:9090']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alert rules (uncomment and customize as needed)
# groups:
# - name: example
#   rules:
#   - alert: HighErrorRate
#     expr: rate(mcp_tool_errors_total[5m]) > 0.1
#     for: 10m
#     labels:
#       severity: warning
#     annotations:
#       summary: "High error rate detected"
#       description: "High error rate detected in security MCP server"
